spring:
  messages:
    basename: messages
    encoding: UTF-8
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # create / create-drop / validate / none도 가능
    show-sql: true
    properties:
      hibernate:
        format_sql: true